# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: f:/ax7015/demo/ibert_test/ibert_ex/imports/example_ibert.xdc

# XDC: new/pins.xdc

# IP: ip/ibert/ibert.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ibert || ORIG_REF_NAME==ibert} -quiet] -quiet
