set_property SRC_FILE_INFO {cfile:f:/ax7015/hdmi_loop/hdmi_loop.srcs/sources_1/ip/sys_pll/sys_pll.xdc rfile:../hdmi_loop.srcs/sources_1/ip/sys_pll/sys_pll.xdc id:1 order:EARLY scoped_inst:sys_pll_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:F:/ax7015/hdmi_loop/hdmi_loop.srcs/constrs_1/new/hdmi_loop.xdc rfile:../hdmi_loop.srcs/constrs_1/new/hdmi_loop.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.2
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {vout_data[*]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports vout_de]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports vout_hs]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports vout_vs]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA16  [get_ports vin_clk]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {vin_data[*]}]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports vin_de]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports vin_hs]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports vin_vs]
