set_property SRC_FILE_INFO {cfile:f:/ax7015/demo/ibert_test/ibert_ex/imports/example_ibert.xdc rfile:../../../imports/example_ibert.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:f:/ax7015/demo/ibert_test/ibert_ex/ibert_ex.srcs/constrs_1/new/pins.xdc rfile:../../../ibert_ex.srcs/constrs_1/new/pins.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y0 [get_cells u_ibert_core/inst/QUAD[0].u_q*/CH[0].u_ch/u_gtpe2_channel]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y1 [get_cells u_ibert_core/inst/QUAD[0].u_q*/CH[1].u_ch/u_gtpe2_channel]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y2 [get_cells u_ibert_core/inst/QUAD[0].u_q*/CH[2].u_ch/u_gtpe2_channel]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y3 [get_cells u_ibert_core/inst/QUAD[0].u_q*/CH[3].u_ch/u_gtpe2_channel]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_COMMON_X0Y0 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_gtpe2_common]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y0 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_clocking/local_txusr.u_txusr]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y1 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_clocking/rx_ind.u_rxusr0]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y2 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_clocking/rx_ind.u_rxusr1]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y3 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_clocking/rx_ind.u_rxusr2]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y4 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_clocking/rx_ind.u_rxusr3]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y0 [get_cells u_buf_q0_clk0]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y1 [get_cells u_buf_q0_clk1]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {tx_disable[0]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports {tx_disable[1]}]
